format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$character"""

scan_timeout = 10

palette = "umbra"

[palettes.umbra]
aurora = "#4caf8f"
nebula = "#61b8d6"
nova = "#9d7cd8"
solar = "#ff9c6a"
stellar = "#e4bf7f"
aldebaran = "#e65a5a"
celaeno = "#e6a2a2"
helios = "#80c7db"
io = "#b794e6"
corona = "#e8e8e8"
halo = "#909090"
twilight = "#3b4b5f"
umbra = "#121218"

[username]
style_user = "bg:aurora fg:umbra"
style_root = "bg:aldebaran fg:corona"
format = "[ $user ]($style)"
show_always = true

[hostname]
ssh_only = false
format = "[ @$hostname ]($style)"
trim_at = "."
style = "bg:nebula fg:umbra"
aliases = { "marcus-mbp" = "home" }

[directory]
style = "bg:nova fg:umbra"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"
read_only = " 󰌾"
read_only_style = "bg:nova fg:aldebaran"

[directory.substitutions]
Documents = '󰈙'
Downloads = ' '
Music = ' '
Pictures = ' '

[git_branch]
symbol = " "
style = "bg:stellar fg:umbra"
format="[ $symbol$branch ]($style)"

[git_status]
style = "bg:twilight fg:corona"
format = '([\[$all_status$ahead_behind\] ]($style))'
conflicted = "=${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[git_state]
style = "bg:solar fg:umbra"
format= '\([$state( $progress_current/$progress_total)]($style)\)'

[cmd_duration]
min_time = 500
style = "bg:twilight fg:corona"
format = '[ took $duration ]($style)'

[python]
symbol = " "
style = "bg:io fg:umbra"
format = '[ $symbol${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'

[nodejs]
symbol = "󰎙 "
style = "bg:aurora fg:umbra"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = "󱘗 "
style = "bg:solar fg:umbra"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:nebula fg:umbra"
format = '[ $symbol($version) ]($style)'

[character]
success_symbol = "[❯](aurora)"
error_symbol = "[❯](aldebaran)"
vimcmd_symbol = "[❮](stellar)"

[line_break]
disabled = false

[os]
format = "[ $symbol]($style)"
style = "bg:celaeno fg:umbra"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

